### ISSUE TITLE
Make everything customizable

### ISSUE THREAD

**Issue by robertwestbury** [Moderatex/Super-Mod#25]
**Is your feature request related to a problem? Please describe.**
Not sure if this is temporary, but all of the thresholds are set in code and unconfigurable.
**Describe the solution you'd like**
Them all being configurable

**Comment by Robinlemon** [comment]
I see no point in making everything configurable since this should only run inside Moderatex infrastructure; authentication details are configurable for continuous integration and production deployment purposes

**Comment by robertwestbury** [comment]
No I mean like the percentage of caps in a message for a user to get timed out and stuff like that @Robinlemon

**Comment by Robinlemon** [comment]
@robertwestbury Ah! Will be customisable at https://moderatex.com/dashboard when I get around to making it. You are right - everything will be customisable.
